### PR TITLE
[Published] Create ERC721A Module

### PR DESCRIPTION
**Pull request by darkty0x**
- contracts
- test
- package.json
- README

### CODE REVIEW

**Comment by Top-Kraken** [comment]
Could you let me know why you used old version of ERC721A?
https://github.com/chiru-labs/ERC721A
I think this one is the latest version of ERC721A and your one looks old one
For example
In Chiru Labs ERC721A, they updated _tokenApprovals by using TokenApprovalRef structure.
You are using
```
mapping(uint256 => address) private _tokenApprovals;
```

Bu in Chirus Labs ERC721A
```
// Reference type for token approval.
struct TokenApprovalRef {
    address value;
}
...
mapping(uint256 => TokenApprovalRef) private _tokenApprovals;
```
You could find out the reason in the following.
https://github.com/chiru-labs/ERC721A/pull/364

Thanks,
cc @hitsuji-haneta @kazunetakeda25

**Comment by smart-ticky** [comment]
remove empty function. 
Line 94:101
`    /**
     * @dev Connect to other contracts
     */
    function connectToOtherContracts(address[] calldata _contracts)
        public
        override
        onlyOwner
    {}`

**Comment by smart-ticky** [comment]
> connectToOtherContracts is defined in IBunzz and I overrided this interface, so If I dont override this function, error will occur.

Yes. but you didn't use the connect function.
So I suggest you remove IBunzz interface in the contract.

**Comment by smart-ticky** [comment]
The rest all look good.

**Comment by stefanandy** [comment]
@moco-bunzz do you have any specific/concrete use case in mind for this module ?

**Pull request closed without merging**
